---
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - my_cache
      - run:
          name: "Get test data: ds007"
          command: |
            if [[ ! -d ~/data/ds007 ]]; then
              wget -c -P ${HOME}/downloads/ "https://dl.dropboxusercontent.com/u/4494604/ds007.tar" && \
              mkdir -p ${HOME}/data && \
              tar xf ${HOME}/downloads/ds007.tar -C ${HOME}/data;
            fi
      - run:
          name: Build Docker image
          command: |
            wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/build_docker.sh
            bash build_docker.sh
      - save_cache:
          key: my_cache
          paths:
            - ~/docker
            - ~/data
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - docker/image.tar

  test:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: mkdir -p ${HOME}/outputs/ds007
      - run:
          name: participant 01 02
          command: |
            docker run -ti --rm \
              -v /tmp/workspace/data/ds007:/bids_dataset \
              -v ${HOME}/outputs/ds007:/outputs \
                bids/${CIRCLE_PROJECT_REPONAME,,} \
                  /bids_dataset /outputs participant --participant_label 01 02
          no_output_timeout: 6h
      - run:
          name: participant 03
          command: |
            docker run -ti --rm \
              -v /tmp/workspace/data/ds007:/bids_dataset \
              -v ${HOME}/outputs/ds007:/outputs \
                bids/${CIRCLE_PROJECT_REPONAME,,} \
                  /bids_dataset /outputs participant --participant_label 03
          no_output_timeout: 6h
      - run:
          name: group level
          command: |
            docker run -ti --rm \
              -v /tmp/workspace/data/ds007:/bids_dataset \
              -v ${HOME}/outputs/ds007:/outputs \
                bids/${CIRCLE_PROJECT_REPONAME,,} \
                  /bids_dataset /outputs group --participant_label 01 02 03
          no_output_timeout: 6h

  deploy:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: docker load -i /tmp/workspace/docker/image.tar
      - run:
          name: push to dockerhub
          command: |
            wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/push_docker.sh
            bash push_docker.sh

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/

# VS Code Extension Version: 1.5.1
