general:
    artifacts:
        - "~/outputs"
machine:
    services:
        - docker

dependencies:
    cache_directories:
    - "~/docker"
    - "~/data"

    override:
        - if [[ ! -d ~/data/ds007 ]]; then wget -c -P ${HOME}/downloads/ "https://dl.dropboxusercontent.com/u/4494604/ds007.tar" && mkdir -p ${HOME}/data && tar xf ${HOME}/downloads/ds007.tar -C ${HOME}/data; fi
        - if [[ -e ~/docker/image.tar ]]; then docker load -i ~/docker/image.tar; fi
        - git describe --tags > version
        - docker build -t bids/${CIRCLE_PROJECT_REPONAME,,} . :
            timeout: 21000
        - mkdir -p ~/docker; docker save "bids/${CIRCLE_PROJECT_REPONAME,,}" > ~/docker/image.tar
        - mkdir -p ${HOME}/outputs/ds007

test:
    override:
        - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds007:/bids_dataset -v ${HOME}/outputs/ds007:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs participant --participant_label 01 02  :
            timeout: 41600
        - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds007:/bids_dataset -v ${HOME}/outputs/ds007:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs participant --participant_label 03  :
            timeout: 41600
        - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds007:/bids_dataset -v ${HOME}/outputs/ds007:/outputs bids/${CIRCLE_PROJECT_REPONAME,,} /bids_dataset /outputs group --participant_label 01 02 03 :
            timeout: 41600


deployment:
  hub:
    owner: BIDS-Apps
    tag: /.*/
    commands:
      - if [[ -n "$DOCKER_PASS" ]]; then docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS && docker push bids/${CIRCLE_PROJECT_REPONAME,,}:latest; fi :
          timeout: 21600
      - if [[ -n "$DOCKER_PASS" ]]; then docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS && docker tag bids/${CIRCLE_PROJECT_REPONAME,,} bids/${CIRCLE_PROJECT_REPONAME,,}:$CIRCLE_TAG && docker push bids/${CIRCLE_PROJECT_REPONAME,,}:$CIRCLE_TAG; fi :
          timeout: 21600
